// Loads static data from JSON files in public/data/
// These files are committed to the repo and served by the CDN.
// They never change at runtime — React Query caches them forever.

import type { Fixture, FixtureContext, Group, MatchResult, Rating, Team, SquadStrengthEntry } from '../types/domain';
import type { TacticalProfile } from '../engine/models/tactical-matchup-model';

interface CompactResults {
  cols: string[];
  rows: [string, string, string, number, number, string, boolean][];
}

export interface SquadPlayer {
  name: string;
  key:  string;
  pos:  'Goalkeeper' | 'Defender' | 'Midfielder' | 'Attacker' | 'Unknown';
}

async function fetchJson<T>(file: string): Promise<T> {
  const res = await fetch(`./data/${file}`);
  if (!res.ok) throw new Error(`No se pudo cargar ${file}: ${res.status}`);
  return res.json() as Promise<T>;
}

export const loadStaticTeams    = () => fetchJson<Team[]>('teams.json');
export const loadStaticGroups   = () => fetchJson<Group[]>('groups.json');
export const loadStaticFixtures = () => fetchJson<Fixture[]>('fixtures.json');
export const loadStaticRatings  = () => fetchJson<Rating[]>('ratings.json');

// Generated by scripts/build-context.mjs at deploy time from ESPN + OpenFootball.
// Returns [] if the file exists but is empty (build script found no injuries).
export const loadStaticFixtureContexts = () =>
  fetchJson<FixtureContext[]>('fixture-contexts.json').catch(() => [] as FixtureContext[]);

// Squad rosters with player positions — generated at deploy time from OpenFootball CC0 data.
export const loadStaticSquads = () =>
  fetchJson<Record<string, SquadPlayer[]>>('squads.json').catch(() => ({} as Record<string, SquadPlayer[]>));

// Squad strength data: market value, top-5 league count, UCL players per national team.
export const loadStaticSquadStrength = () =>
  fetchJson<Record<string, SquadStrengthEntry>>('squad-strength.json')
    .catch(() => ({} as Record<string, SquadStrengthEntry>));

// Tactical profiles: per-team formation, style, and matchup attributes.
export const loadStaticTacticalProfiles = () =>
  fetchJson<Record<string, TacticalProfile>>('tactical-profiles.json')
    .catch(() => ({} as Record<string, TacticalProfile>));

export async function loadStaticResults(): Promise<MatchResult[]> {
  const compact = await fetchJson<CompactResults>('historical_results.json');
  return compact.rows.map(([date, home_id, away_id, home_goals, away_goals, tournament, neutral]) => ({
    id: `${home_id}-${away_id}-${date}`,
    home_team_id: home_id,
    away_team_id: away_id,
    home_goals,
    away_goals,
    date,
    tournament,
    neutral,
  }));
}
